image: python:3.8.1

stages:
  - test
  - staging
  - deploy

codequality:
  stage: test
  before_script:
    - "pip install -r requirements.txt"
  script:
    - "flake8"

test:
  stage: test
  before_script:
    - "pip install -r requirements.txt"
  script:
    - "python manage.py test"

staging:
  stage: staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master
