# Generated by Django 3.0.8 on 2020-07-17 15:01

from django.db import migrations, models
import utils.rstring


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(default=utils.rstring.make_id, editable=False, max_length=5, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1)),
                ('missed_letters', models.CharField(blank=True, max_length=255)),
                ('correct_letters', models.CharField(blank=True, max_length=255)),
                ('secret_word', models.CharField(max_length=255)),
                ('secret_set', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
