# Generated by Django 3.0.8 on 2020-07-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
